services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=identity'
      - 'POSTGRES_PASSWORD=220503'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'